#!/usr/bin/env ruby

require 'rubygems'
require 'hpricot'
require 'cgi'

def grab_page(num)
  `osascript -e '
  on run
    tell application "Safari"
      open location "http://games.groups.yahoo.com/group/gooeyblob/message/#{1}?source=1&var=1&l=1"
      delay 10
      set page_source to source of front document as string
      close front document
    end tell
    return page_source
  end run'`
end

def rip_email(raw)
  raw = Hpricot(raw).search('td.source').text.split(/\n/)
  unless raw.length == 0
    headers, body = Hash.new, Array.new
    while raw.last.strip.empty?
      raw.pop
    end
    while raw.first.strip.empty?
      raw.slice!(0)
    end
    header = true
    raw.each do |line|
      if header
        if line.empty?
          header = false
        else
          line.scan(/^(\S+)\s*:\s*(.*)$/) do |field, value|
            if headers.has_key?(field.downcase)
              headers[field.downcase] += "\n" + value
            else
              headers[field.downcase] = value
            end
          end
        end
      else
        body << line
      end
    end
  end
  return body ? [headers, body.join("\n")] : nil
end

File.open('output/gooey-blob.html', 'w') do |file|
  file.puts "<!DOCTYPE html>\n\n<html>\n<head>\n<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\n<link rel='stylesheet' href='gooey-blob.css' type='text/css' media='screen'>\n<title>Gooey Blob Group</title>\n</head>\n<body>"
  (1..(ARGV[0].to_i)).each do |num|
    print "Grabbing page #{num} from Safari... "
    raw = grab_page(num)
    puts "done."
    print "Parsing page #{num}... "
    message = rip_email(raw)
    puts "done."
    if message
      print "Adding to unified page... "
      file.puts "<div class='message'>"
      file.puts "<div class='header'>"
      file.puts "<span class='subject'>#{CGI.escapeHTML(message[0]['subject'])}</span>" if message[0]['subject']
      file.puts "<span class='date'>#{CGI.escapeHTML(message[0]['date'])}</span>"if message[0]['date']
      file.puts "<div class='from'>#{CGI.escapeHTML(message[0]['from'])}</div>" if message[0]['from']
      file.puts "</div>"
      file.puts "<div class='message-body'>"
      file.puts "<pre>"
      file.puts CGI.escapeHTML(message[1])
      file.puts "</pre>"
      file.puts "</div>"
      file.puts "</div>"
      puts "done."
    else
      puts "No message found, skipping."
    end
  end
  file.puts "</body>\n</html>"
end