#!/usr/bin/osascript

on run argv
  tell application "Safari"
    open location "http://games.groups.yahoo.com/group/gooeyblob/message/" & (item 1 of argv) & "?source=1&var=1&l=1"
    delay 10
    set page_source to source of front document as string
    close front document
  end tell
  return page_source
end run