#!/usr/bin/env ruby

require 'rubygems'
require 'json'
require 'cgi'

File.open('unifier_out/gooey-blob.html', 'w') do |file|
  file.puts "<!DOCTYPE html>\n\n<html>\n<head>\n<meta http-equiv='Content-Type' content='text/html; charset=utf-8'>\n<link rel='stylesheet' href='gooey-blob.css' type='text/css' media='screen'>\n<title>Gooey Blob Group</title>\n</head>\n<body>"
  Dir.glob('parser_out/message_*').each do |filename|
    message =  JSON.parse(File.open(filename, 'r').read)
    file.puts "<div class='message'>"
    file.puts "<div class='header'>"
    file.puts "<span class='subject'>#{CGI.escapeHTML(message[0]['subject'])}</span>"
    file.puts "<span class='date'>#{CGI.escapeHTML(message[0]['date'])}</span>"
    file.puts "<div class='from'>#{CGI.escapeHTML(message[0]['from'])}</div>"
    file.puts "</div>"
    file.puts "<div class='message-body'>"
    file.puts "<pre>"
    file.puts CGI.escapeHTML(message[1])
    file.puts "</pre>"
    file.puts "</div>"
    file.puts "</div>"
  end
  file.puts "</body>\n</html>"
end